⚡some changes for effiencty on Debian stable🍥

diff --git a/.local/bin/update-discord b/.local/bin/update-discord
--- a/.local/bin/update-discord
+++ b/.local/bin/update-discord
@@ -5,18 +5,24 @@ platform="linux"
 
 while getopts ":f:p:h" opt; do
   case $opt in
-    f) format="$OPTARG" ;;
-    p) platform="$OPTARG" ;;
-    h)
-      echo "Usage: ./script.sh [-f <format>] [-p <platform>] [-h]"
-      echo "Options:"
-      echo "  -f <format>   Specify the download format (default: deb)"
-      echo "  -p <platform> Specify the platform (default: linux)"
-      echo "  -h            Display this help message"
-      exit 0
-      ;;
-    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
-    :) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
+  f) format="$OPTARG" ;;
+  p) platform="$OPTARG" ;;
+  h)
+    echo "Usage: ./script.sh [-f <format>] [-p <platform>] [-h]"
+    echo "Options:"
+    echo "  -f <format>   Specify the download format (default: deb)"
+    echo "  -p <platform> Specify the platform (default: linux)"
+    echo "  -h            Display this help message"
+    exit 0
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
+  :)
+    echo "Option -$OPTARG requires an argument." >&2
+    exit 1
+    ;;
   esac
 done
 
@@ -27,4 +33,6 @@ output_file="/tmp/discord.deb"
 curl -L --output $output_file $download_url
 
 # Install the downloaded package using apt
-sudo apt install -y $output_file
+sudo nala insttall -y $output_file
+$SHELL
+
